name: totseg
channels:
  - conda-forge
  - defaults

dependencies:
  # Core packages installed via Conda
  - python=3.10
  - dask==2025.11.0
  - numpy==2.2.6
  - pandas==2.3.2
  - scipy==1.15.3
  - scikit-image==0.25.2
  - scikit-learn
  - matplotlib
  - tqdm
  - pip==25.2
  
  # Pip-only packages
  - pip:
      - dbdicom==0.3.14
      - vreg==0.0.11
      - pydmr==0.0.5
      - pyvista
      - miblab[dlseg]